// PG: Family-friendly but funny/absurd things to draw
export const PG = [
  "stepping on a lego",
  "a cat judging you",
  "awkward family photo",
  "dad dancing",
  "a dog wearing pants",
  "eating spaghetti on a date",
  "existential crisis",
  "a pigeon with a briefcase",
  "grandma on a skateboard",
  "passive aggressive note",
  "crying in the shower",
  "an evil snowman",
  "wifi not working",
  "monday morning",
  "burnt toast",
  "a haunted house",
  "sleepwalking",
  "running with scissors",
  "a fish out of water",
  "talking to plants",
  "forgetting your password",
  "a surprise birthday party",
  "a very long receipt",
  "sitting on a cactus",
  "arguing with a parrot",
  "losing one sock",
  "a penguin in the desert",
  "accidentally waving back",
  "eating cereal at midnight",
  "pretending to be busy",
  "a bear riding a bicycle",
  "sneezing with eyes open",
  "waiting for the bus",
  "tangled headphones",
  "a llama at the dentist",
  "screaming into a pillow",
  "peeling a banana wrong",
  "a shark in a swimming pool",
  "walking into a glass door",
  "a cat chasing a laser",
  "spilling coffee on your laptop",
  "an octopus playing drums",
  "fear of clowns",
  "a giraffe with a sore throat",
  "eating soup with a fork",
  "sleeping through your alarm",
  "a frog on a unicycle",
  "dropping your ice cream",
  "a raccoon stealing trash",
  "robot learning to dance",
  "an elephant in a tiny car",
  "slipping on a banana peel",
  "a snowball fight",
  "catching fireflies",
  "a wizard doing taxes",
  "dragon with hiccups",
  "alien trying human food",
  "a horse in a hospital",
  "looking for your glasses",
  "singing in the rain",
  "stuck in an elevator",
  "a turtle winning a race",
  "angry birds",
  "a cow jumping over the moon",
  "building a blanket fort",
  "a hamster on a wheel",
  "yelling at clouds",
  "standing on a lego minefield",
  "a squirrel hoarding nuts",
  "tripping up the stairs",
  "a duck in sunglasses",
  "failing at yoga",
  "being chased by a goose",
  "a snake wearing a hat",
  "the floor is lava",
  "invisible man eating pizza",
  "a ghost getting scared",
  "fighting over the remote",
  "a unicorn at a job interview",
];

// PG-13: Mild innuendo, embarrassing situations, edgy humor
export const PG13 = [
  "the walk of shame",
  "a midlife crisis",
  "ugly crying in public",
  "bad tinder date",
  "drunk texting your ex",
  "beer goggles",
  "walk of fame to walk of shame",
  "tramp stamp",
  "a wardrobe malfunction",
  "walk in on your parents",
  "accidental reply all",
  "farting in an elevator",
  "a plumber showing crack",
  "shotgunning a beer",
  "the morning after",
  "skinny dipping",
  "doing the walk of shame",
  "waking up with regrets",
  "a cougar on the prowl",
  "sugar daddy",
  "seven minutes in heaven",
  "walk into the wrong bathroom",
  "pantsed in public",
  "a bad spray tan",
  "twerking at a funeral",
  "flirting with the bartender",
  "a muffin top",
  "going commando",
  "butt dial your boss",
  "dancing on the table",
  "a coyote ugly situation",
  "body shots",
  "a hickey you can not hide",
  "catching your roommate",
  "wearing beer goggles",
  "a streaker at a football game",
  "waxing gone wrong",
  "the wobble of shame",
  "clogging someone elses toilet",
  "shotgun wedding",
  "drunk karaoke",
  "a bad pickup line",
  "spending rent money on brunch",
  "ghosting someone",
  "thirst trap",
  "sending a risky text",
  "a regrettable tattoo",
  "walk of shame in heels",
  "a toilet paper trail",
  "your search history",
  "peeing in the pool",
  "a gold digger",
  "accidentally liking an old photo",
  "sleeping with the boss",
  "beer pong champion",
  "a fake ID",
  "throwing up in an uber",
  "killing the vibe",
  "drunken confession",
  "hot mess express",
  "catfishing",
  "booty call",
  "friends with benefits",
  "a stage five clinger",
  "tequila makes her clothes fall off",
  "that one friend who can not handle liquor",
  "losing a bet",
  "truth or dare gone wrong",
  "spin the bottle",
  "swiping right on your teacher",
  "falling off the mechanical bull",
  "drunk online shopping",
  "hangover from hell",
  "liquid courage",
  "the champagne room",
  "a lap dance from grandma",
  "flashing the camera",
  "a walk of shame uber",
  "never have I ever",
  "making out in the club",
];

// R: Adult humor, crude, raunchy (but still drawable/guessable)
export const R = [
  "a stripper pole in church",
  "netflix and chill",
  "morning wood",
  "a one night stand",
  "angry sex",
  "the casting couch",
  "walk of shame no pants",
  "scissoring",
  "sixty nine",
  "a walk in closet orgy",
  "mile high club",
  "eating ass",
  "a happy ending massage",
  "getting caught watching porn",
  "butt plug",
  "walk of shame with a traffic cone",
  "two girls one cup",
  "a glory hole",
  "motorboating",
  "road head",
  "blue balls",
  "whiskey dick",
  "a strap on",
  "the money shot",
  "friends with benefits plus dental",
  "a walk of shame through church",
  "afternoon delight",
  "bow chicka wow wow",
  "hung like a horse",
  "the shocker",
  "Netflix and actually chill",
  "a nip slip at the grammys",
  "a dirty sanchez",
  "pulling out game weak",
  "doggy style",
  "fifty shades of grey",
  "an awkward boner",
  "the walk of shame in a costume",
  "getting frisky in the fitting room",
  "a peeping tom",
  "skinny dipping with sharks",
  "size does matter",
  "body count",
  "a nooner",
  "pillow biter",
  "tea bagging",
  "a booty call at three am",
  "reverse cowgirl",
  "the walk of shame past your neighbors",
  "handcuffs in the bedroom",
  "a brazilian wax gone wrong",
  "the orgasm face",
  "three way awkwardness",
  "walk of shame missing underwear",
  "a drunk hookup with your ex",
  "a vibrating phone in your pocket",
  "accidental sext to mom",
  "bend over boyfriend",
  "naked and afraid",
  "pants off dance off",
  "a strip poker loss",
  "the money maker",
  "walk of shame with a pizza box",
  "caught with your pants down",
  "the shocker face",
  "a nude beach mishap",
  "the helicopter",
  "a quickie in the closet",
  "going down on the titanic",
  "a disappointing first time",
];

// Build combined lists for each rating level
export const PROMPTS = {
  pg: PG,
  pg13: [...PG, ...PG13],
  r: [...PG, ...PG13, ...R],
};
